### PR TITLE
Fix links with vdir

### PR DESCRIPTION
**Pull request by grahamrhay**
Interestingly, the links to alternate formats returned by Nancy (e.g. with the menu) were correct. So I've altered my solution a bit. All the tests pass now, but it's still a bit hacky!

### CODE REVIEW

**Comment by horsdal** [comment]
Would you mind adding couple of tests verifying your changes? It seems to work fine, but still...

**Comment by grahamrhay** [comment]
You shouldn't have to ask, I hang my head in shame.

The tests don't really prove much though :(

**Comment by horsdal** [comment]
Thanks! (goes for the other two pull req's too)

**Comment by grahamrhay** [comment]
Just in case you're interested, the reason for all this is that I've created a UI (https://github.com/grahamrhay/restbucks-ui) for it. 

It's a single page js app, that should be compatible with all restbucks-on-\* implementations :)

**Comment by horsdal** [comment]
That's awesome. Will chech that out.

onsdag den 3. oktober 2012 skrev Graham Hay :

> Just in case you're interested, the reason for all this is that I've
> created a UI (https://github.com/grahamrhay/restbucks-ui) for it.
> 
> It's a single page js app, that should be compatible with all
> restbucks-on-\* implementations :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/horsdal/Restbucks-on-Nancy/pull/2#issuecomment-9101458.

## 

---

Christian Horsdal Gammelgaard
Sandøgade 4
8200 Århus N

+45 87 39 07 40
+45 28 89 65 02

**Comment by grahamrhay** [comment]
Be warned, I'm not a designer. And there's only so much Bootstrap can do for you!

**Pull request merged**
