### PR TITLE
Horrific hack to return enums as camel cased strings in json responses

### PR DESCRIPTION
**Pull request by grahamrhay**
One more :)

### CODE REVIEW

**Comment by horsdal** [comment]
Sorry this seems to be too halfed baked to make it in. Even in this which is only a demo after all.

**Comment by grahamrhay** [comment]
No worries. Unfortunately, unless Nancy offers a better way to control json serialization, it's the best I can do :(

**Comment by horsdal** [comment]
Well, I don't think your approach of creating and registering your own json
serializer is wrong. It's just that it seems to be only half implemented.

**Comment by grahamrhay** [comment]
It's wrong in many different ways :)

You mean inbound? Yes, good point, I forgot about that! I'll look into it.

**Comment by horsdal** [comment]
How is it so wrong? Enlighten me :)

**Comment by grahamrhay** [comment]
Have a look at the nested class, in the converter.

**Comment by horsdal** [comment]
Yeah, I saw that. But couldn't that be implemented properly?

**Comment by grahamrhay** [comment]
Depends what you mean by properly, I guess. That's the only "solution" I could find, without making changes to Nancy. I'd be happy to be proven wrong though :)

The converter is expected to return a dictionary (i.e. json props, { foo: 1, bar: "" }); so if you want to return just a value, you have to do something unpleasant.

That's partly why I didn't do the inbound bit, I'm not sure it would even work going that way. Also, I forgot :)

I raised an issue with Nancy, but I don't really have a solution to offer :( Json.Net uses an attribute, as does DataContracts. But, when you've already got xml attributes on the DTO, that road leads to madness (attribute soup).

**Comment by logiclrd** [comment]
Would this simplify your life?:

https://github.com/NancyFx/Nancy/pull/1310

I also needed to convert data to/from a JSON primitive rather than a JSON object, so I plumbed in a new type of converter specifically for that task. :-)

**Pull request closed without merging**
